package com.weichaishi.model;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

@Table(name="labac_projects")
public class LabacProjects implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_ID
     *
     * @mbggenerated
     */
    @Id
    private Integer projectId;

    @Transient
    private List<LabacTasks> labacTasks;

    public List<LabacTasks> getLabacTasks() {
        return labacTasks;
    }

    public void setLabacTasks(List<LabacTasks> labacTasks) {
        this.labacTasks = labacTasks;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_NAME
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_DESC
     *
     * @mbggenerated
     */
    private String projectDesc;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date projectCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_UPDATE_TIME
     *
     * @mbggenerated
     */
    private Date projectUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_COMMENTS
     *
     * @mbggenerated
     */
    private String projectComments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_OWNER_CUSTOMER_ID
     *
     * @mbggenerated
     */
    private BigDecimal projectOwnerCustomerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_QUANTITY
     *
     * @mbggenerated
     */
    private Long projectQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal projectValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_TYPE
     *
     * @mbggenerated
     */
    private Short projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_LOCATION_FLAG
     *
     * @mbggenerated
     */
    private Short projectLocationFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_DISPLAY_SIZE
     *
     * @mbggenerated
     */
    private Short projectDisplaySize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_ORDER
     *
     * @mbggenerated
     */
    private BigDecimal projectOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_CATEGORIES
     *
     * @mbggenerated
     */
    private String projectCategories;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_FLAG
     *
     * @mbggenerated
     */
    private Short projectFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_ICON
     *
     * @mbggenerated
     */
    private String projectIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_STATUS_INDICATOR
     *
     * @mbggenerated
     */
    private Short projectStatusIndicator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_QUANTITY_TRIED
     *
     * @mbggenerated
     */
    private BigDecimal projectQuantityTried;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_3RD_PARTY_REVIEW_FLAG
     *
     * @mbggenerated
     */
    @Column(name = "project_3rd_party_review_flag")
    private Short project3rdPartyReviewFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_REVIEW_INSTRUCTION
     *
     * @mbggenerated
     */
    private String projectReviewInstruction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_REJECT_REASONS
     *
     * @mbggenerated
     */
    private Object projectRejectReasons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_REWORK_REASONS
     *
     * @mbggenerated
     */
    private Object projectReworkReasons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_PREAPPROVE_REASONS
     *
     * @mbggenerated
     */
    private Object projectPreapproveReasons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_DIFFICULTY_LEVEL
     *
     * @mbggenerated
     */
    private Short projectDifficultyLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_CATEGORIES2
     *
     * @mbggenerated
     */
    private String projectCategories2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_PLAN_END_DATE
     *
     * @mbggenerated
     */
    private Date projectPlanEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_ACTUAL_END_DATE
     *
     * @mbggenerated
     */
    private Date projectActualEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.SALE_ID
     *
     * @mbggenerated
     */
    private Short saleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_SUBJECT
     *
     * @mbggenerated
     */
    private String projectSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_DETAIL
     *
     * @mbggenerated
     */
    private String projectDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_MAX_VALUE
     *
     * @mbggenerated
     */
    private BigDecimal projectMaxValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_ICON2
     *
     * @mbggenerated
     */
    private String projectIcon2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_CATEGORY_FLAG
     *
     * @mbggenerated
     */
    private Short projectCategoryFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_LOCATIONS_FLAG
     *
     * @mbggenerated
     */
    private Short projectLocationsFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LABAC_PROJECTS.PROJECT_GROUP_ID
     *
     * @mbggenerated
     */
    private Short projectGroupId;

    public Integer getProjectId() {
        return projectId;
    }

    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_NAME
     *
     * @return the value of LABAC_PROJECTS.PROJECT_NAME
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_NAME
     *
     * @param projectName the value for LABAC_PROJECTS.PROJECT_NAME
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_DESC
     *
     * @return the value of LABAC_PROJECTS.PROJECT_DESC
     *
     * @mbggenerated
     */
    public String getProjectDesc() {
        return projectDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_DESC
     *
     * @param projectDesc the value for LABAC_PROJECTS.PROJECT_DESC
     *
     * @mbggenerated
     */
    public void setProjectDesc(String projectDesc) {
        this.projectDesc = projectDesc == null ? null : projectDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_CREATE_TIME
     *
     * @return the value of LABAC_PROJECTS.PROJECT_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getProjectCreateTime() {
        return projectCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_CREATE_TIME
     *
     * @param projectCreateTime the value for LABAC_PROJECTS.PROJECT_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setProjectCreateTime(Date projectCreateTime) {
        this.projectCreateTime = projectCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_UPDATE_TIME
     *
     * @return the value of LABAC_PROJECTS.PROJECT_UPDATE_TIME
     *
     * @mbggenerated
     */
    public Date getProjectUpdateTime() {
        return projectUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_UPDATE_TIME
     *
     * @param projectUpdateTime the value for LABAC_PROJECTS.PROJECT_UPDATE_TIME
     *
     * @mbggenerated
     */
    public void setProjectUpdateTime(Date projectUpdateTime) {
        this.projectUpdateTime = projectUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_COMMENTS
     *
     * @return the value of LABAC_PROJECTS.PROJECT_COMMENTS
     *
     * @mbggenerated
     */
    public String getProjectComments() {
        return projectComments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_COMMENTS
     *
     * @param projectComments the value for LABAC_PROJECTS.PROJECT_COMMENTS
     *
     * @mbggenerated
     */
    public void setProjectComments(String projectComments) {
        this.projectComments = projectComments == null ? null : projectComments.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_OWNER_CUSTOMER_ID
     *
     * @return the value of LABAC_PROJECTS.PROJECT_OWNER_CUSTOMER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getProjectOwnerCustomerId() {
        return projectOwnerCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_OWNER_CUSTOMER_ID
     *
     * @param projectOwnerCustomerId the value for LABAC_PROJECTS.PROJECT_OWNER_CUSTOMER_ID
     *
     * @mbggenerated
     */
    public void setProjectOwnerCustomerId(BigDecimal projectOwnerCustomerId) {
        this.projectOwnerCustomerId = projectOwnerCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_QUANTITY
     *
     * @return the value of LABAC_PROJECTS.PROJECT_QUANTITY
     *
     * @mbggenerated
     */
    public Long getProjectQuantity() {
        return projectQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_QUANTITY
     *
     * @param projectQuantity the value for LABAC_PROJECTS.PROJECT_QUANTITY
     *
     * @mbggenerated
     */
    public void setProjectQuantity(Long projectQuantity) {
        this.projectQuantity = projectQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_VALUE
     *
     * @return the value of LABAC_PROJECTS.PROJECT_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getProjectValue() {
        return projectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_VALUE
     *
     * @param projectValue the value for LABAC_PROJECTS.PROJECT_VALUE
     *
     * @mbggenerated
     */
    public void setProjectValue(BigDecimal projectValue) {
        this.projectValue = projectValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_TYPE
     *
     * @return the value of LABAC_PROJECTS.PROJECT_TYPE
     *
     * @mbggenerated
     */
    public Short getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_TYPE
     *
     * @param projectType the value for LABAC_PROJECTS.PROJECT_TYPE
     *
     * @mbggenerated
     */
    public void setProjectType(Short projectType) {
        this.projectType = projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_LOCATION_FLAG
     *
     * @return the value of LABAC_PROJECTS.PROJECT_LOCATION_FLAG
     *
     * @mbggenerated
     */
    public Short getProjectLocationFlag() {
        return projectLocationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_LOCATION_FLAG
     *
     * @param projectLocationFlag the value for LABAC_PROJECTS.PROJECT_LOCATION_FLAG
     *
     * @mbggenerated
     */
    public void setProjectLocationFlag(Short projectLocationFlag) {
        this.projectLocationFlag = projectLocationFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_DISPLAY_SIZE
     *
     * @return the value of LABAC_PROJECTS.PROJECT_DISPLAY_SIZE
     *
     * @mbggenerated
     */
    public Short getProjectDisplaySize() {
        return projectDisplaySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_DISPLAY_SIZE
     *
     * @param projectDisplaySize the value for LABAC_PROJECTS.PROJECT_DISPLAY_SIZE
     *
     * @mbggenerated
     */
    public void setProjectDisplaySize(Short projectDisplaySize) {
        this.projectDisplaySize = projectDisplaySize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_ORDER
     *
     * @return the value of LABAC_PROJECTS.PROJECT_ORDER
     *
     * @mbggenerated
     */
    public BigDecimal getProjectOrder() {
        return projectOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_ORDER
     *
     * @param projectOrder the value for LABAC_PROJECTS.PROJECT_ORDER
     *
     * @mbggenerated
     */
    public void setProjectOrder(BigDecimal projectOrder) {
        this.projectOrder = projectOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_CATEGORIES
     *
     * @return the value of LABAC_PROJECTS.PROJECT_CATEGORIES
     *
     * @mbggenerated
     */
    public String getProjectCategories() {
        return projectCategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_CATEGORIES
     *
     * @param projectCategories the value for LABAC_PROJECTS.PROJECT_CATEGORIES
     *
     * @mbggenerated
     */
    public void setProjectCategories(String projectCategories) {
        this.projectCategories = projectCategories == null ? null : projectCategories.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_FLAG
     *
     * @return the value of LABAC_PROJECTS.PROJECT_FLAG
     *
     * @mbggenerated
     */
    public Short getProjectFlag() {
        return projectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_FLAG
     *
     * @param projectFlag the value for LABAC_PROJECTS.PROJECT_FLAG
     *
     * @mbggenerated
     */
    public void setProjectFlag(Short projectFlag) {
        this.projectFlag = projectFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_ICON
     *
     * @return the value of LABAC_PROJECTS.PROJECT_ICON
     *
     * @mbggenerated
     */
    public String getProjectIcon() {
        return projectIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_ICON
     *
     * @param projectIcon the value for LABAC_PROJECTS.PROJECT_ICON
     *
     * @mbggenerated
     */
    public void setProjectIcon(String projectIcon) {
        this.projectIcon = projectIcon == null ? null : projectIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_STATUS_INDICATOR
     *
     * @return the value of LABAC_PROJECTS.PROJECT_STATUS_INDICATOR
     *
     * @mbggenerated
     */
    public Short getProjectStatusIndicator() {
        return projectStatusIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_STATUS_INDICATOR
     *
     * @param projectStatusIndicator the value for LABAC_PROJECTS.PROJECT_STATUS_INDICATOR
     *
     * @mbggenerated
     */
    public void setProjectStatusIndicator(Short projectStatusIndicator) {
        this.projectStatusIndicator = projectStatusIndicator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_QUANTITY_TRIED
     *
     * @return the value of LABAC_PROJECTS.PROJECT_QUANTITY_TRIED
     *
     * @mbggenerated
     */
    public BigDecimal getProjectQuantityTried() {
        return projectQuantityTried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_QUANTITY_TRIED
     *
     * @param projectQuantityTried the value for LABAC_PROJECTS.PROJECT_QUANTITY_TRIED
     *
     * @mbggenerated
     */
    public void setProjectQuantityTried(BigDecimal projectQuantityTried) {
        this.projectQuantityTried = projectQuantityTried;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_3RD_PARTY_REVIEW_FLAG
     *
     * @return the value of LABAC_PROJECTS.PROJECT_3RD_PARTY_REVIEW_FLAG
     *
     * @mbggenerated
     */
    public Short getProject3rdPartyReviewFlag() {
        return project3rdPartyReviewFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_3RD_PARTY_REVIEW_FLAG
     *
     * @param project3rdPartyReviewFlag the value for LABAC_PROJECTS.PROJECT_3RD_PARTY_REVIEW_FLAG
     *
     * @mbggenerated
     */
    public void setProject3rdPartyReviewFlag(Short project3rdPartyReviewFlag) {
        this.project3rdPartyReviewFlag = project3rdPartyReviewFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_REVIEW_INSTRUCTION
     *
     * @return the value of LABAC_PROJECTS.PROJECT_REVIEW_INSTRUCTION
     *
     * @mbggenerated
     */
    public String getProjectReviewInstruction() {
        return projectReviewInstruction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_REVIEW_INSTRUCTION
     *
     * @param projectReviewInstruction the value for LABAC_PROJECTS.PROJECT_REVIEW_INSTRUCTION
     *
     * @mbggenerated
     */
    public void setProjectReviewInstruction(String projectReviewInstruction) {
        this.projectReviewInstruction = projectReviewInstruction == null ? null : projectReviewInstruction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_REJECT_REASONS
     *
     * @return the value of LABAC_PROJECTS.PROJECT_REJECT_REASONS
     *
     * @mbggenerated
     */
    public Object getProjectRejectReasons() {
        return projectRejectReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_REJECT_REASONS
     *
     * @param projectRejectReasons the value for LABAC_PROJECTS.PROJECT_REJECT_REASONS
     *
     * @mbggenerated
     */
    public void setProjectRejectReasons(Object projectRejectReasons) {
        this.projectRejectReasons = projectRejectReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_REWORK_REASONS
     *
     * @return the value of LABAC_PROJECTS.PROJECT_REWORK_REASONS
     *
     * @mbggenerated
     */
    public Object getProjectReworkReasons() {
        return projectReworkReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_REWORK_REASONS
     *
     * @param projectReworkReasons the value for LABAC_PROJECTS.PROJECT_REWORK_REASONS
     *
     * @mbggenerated
     */
    public void setProjectReworkReasons(Object projectReworkReasons) {
        this.projectReworkReasons = projectReworkReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_PREAPPROVE_REASONS
     *
     * @return the value of LABAC_PROJECTS.PROJECT_PREAPPROVE_REASONS
     *
     * @mbggenerated
     */
    public Object getProjectPreapproveReasons() {
        return projectPreapproveReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_PREAPPROVE_REASONS
     *
     * @param projectPreapproveReasons the value for LABAC_PROJECTS.PROJECT_PREAPPROVE_REASONS
     *
     * @mbggenerated
     */
    public void setProjectPreapproveReasons(Object projectPreapproveReasons) {
        this.projectPreapproveReasons = projectPreapproveReasons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_DIFFICULTY_LEVEL
     *
     * @return the value of LABAC_PROJECTS.PROJECT_DIFFICULTY_LEVEL
     *
     * @mbggenerated
     */
    public Short getProjectDifficultyLevel() {
        return projectDifficultyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_DIFFICULTY_LEVEL
     *
     * @param projectDifficultyLevel the value for LABAC_PROJECTS.PROJECT_DIFFICULTY_LEVEL
     *
     * @mbggenerated
     */
    public void setProjectDifficultyLevel(Short projectDifficultyLevel) {
        this.projectDifficultyLevel = projectDifficultyLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_CATEGORIES2
     *
     * @return the value of LABAC_PROJECTS.PROJECT_CATEGORIES2
     *
     * @mbggenerated
     */
    public String getProjectCategories2() {
        return projectCategories2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_CATEGORIES2
     *
     * @param projectCategories2 the value for LABAC_PROJECTS.PROJECT_CATEGORIES2
     *
     * @mbggenerated
     */
    public void setProjectCategories2(String projectCategories2) {
        this.projectCategories2 = projectCategories2 == null ? null : projectCategories2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_PLAN_END_DATE
     *
     * @return the value of LABAC_PROJECTS.PROJECT_PLAN_END_DATE
     *
     * @mbggenerated
     */
    public Date getProjectPlanEndDate() {
        return projectPlanEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_PLAN_END_DATE
     *
     * @param projectPlanEndDate the value for LABAC_PROJECTS.PROJECT_PLAN_END_DATE
     *
     * @mbggenerated
     */
    public void setProjectPlanEndDate(Date projectPlanEndDate) {
        this.projectPlanEndDate = projectPlanEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_ACTUAL_END_DATE
     *
     * @return the value of LABAC_PROJECTS.PROJECT_ACTUAL_END_DATE
     *
     * @mbggenerated
     */
    public Date getProjectActualEndDate() {
        return projectActualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_ACTUAL_END_DATE
     *
     * @param projectActualEndDate the value for LABAC_PROJECTS.PROJECT_ACTUAL_END_DATE
     *
     * @mbggenerated
     */
    public void setProjectActualEndDate(Date projectActualEndDate) {
        this.projectActualEndDate = projectActualEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.SALE_ID
     *
     * @return the value of LABAC_PROJECTS.SALE_ID
     *
     * @mbggenerated
     */
    public Short getSaleId() {
        return saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.SALE_ID
     *
     * @param saleId the value for LABAC_PROJECTS.SALE_ID
     *
     * @mbggenerated
     */
    public void setSaleId(Short saleId) {
        this.saleId = saleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_SUBJECT
     *
     * @return the value of LABAC_PROJECTS.PROJECT_SUBJECT
     *
     * @mbggenerated
     */
    public String getProjectSubject() {
        return projectSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_SUBJECT
     *
     * @param projectSubject the value for LABAC_PROJECTS.PROJECT_SUBJECT
     *
     * @mbggenerated
     */
    public void setProjectSubject(String projectSubject) {
        this.projectSubject = projectSubject == null ? null : projectSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_DETAIL
     *
     * @return the value of LABAC_PROJECTS.PROJECT_DETAIL
     *
     * @mbggenerated
     */
    public String getProjectDetail() {
        return projectDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_DETAIL
     *
     * @param projectDetail the value for LABAC_PROJECTS.PROJECT_DETAIL
     *
     * @mbggenerated
     */
    public void setProjectDetail(String projectDetail) {
        this.projectDetail = projectDetail == null ? null : projectDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_MAX_VALUE
     *
     * @return the value of LABAC_PROJECTS.PROJECT_MAX_VALUE
     *
     * @mbggenerated
     */
    public BigDecimal getProjectMaxValue() {
        return projectMaxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_MAX_VALUE
     *
     * @param projectMaxValue the value for LABAC_PROJECTS.PROJECT_MAX_VALUE
     *
     * @mbggenerated
     */
    public void setProjectMaxValue(BigDecimal projectMaxValue) {
        this.projectMaxValue = projectMaxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_ICON2
     *
     * @return the value of LABAC_PROJECTS.PROJECT_ICON2
     *
     * @mbggenerated
     */
    public String getProjectIcon2() {
        return projectIcon2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_ICON2
     *
     * @param projectIcon2 the value for LABAC_PROJECTS.PROJECT_ICON2
     *
     * @mbggenerated
     */
    public void setProjectIcon2(String projectIcon2) {
        this.projectIcon2 = projectIcon2 == null ? null : projectIcon2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_CATEGORY_FLAG
     *
     * @return the value of LABAC_PROJECTS.PROJECT_CATEGORY_FLAG
     *
     * @mbggenerated
     */
    public Short getProjectCategoryFlag() {
        return projectCategoryFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_CATEGORY_FLAG
     *
     * @param projectCategoryFlag the value for LABAC_PROJECTS.PROJECT_CATEGORY_FLAG
     *
     * @mbggenerated
     */
    public void setProjectCategoryFlag(Short projectCategoryFlag) {
        this.projectCategoryFlag = projectCategoryFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_LOCATIONS_FLAG
     *
     * @return the value of LABAC_PROJECTS.PROJECT_LOCATIONS_FLAG
     *
     * @mbggenerated
     */
    public Short getProjectLocationsFlag() {
        return projectLocationsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_LOCATIONS_FLAG
     *
     * @param projectLocationsFlag the value for LABAC_PROJECTS.PROJECT_LOCATIONS_FLAG
     *
     * @mbggenerated
     */
    public void setProjectLocationsFlag(Short projectLocationsFlag) {
        this.projectLocationsFlag = projectLocationsFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LABAC_PROJECTS.PROJECT_GROUP_ID
     *
     * @return the value of LABAC_PROJECTS.PROJECT_GROUP_ID
     *
     * @mbggenerated
     */
    public Short getProjectGroupId() {
        return projectGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LABAC_PROJECTS.PROJECT_GROUP_ID
     *
     * @param projectGroupId the value for LABAC_PROJECTS.PROJECT_GROUP_ID
     *
     * @mbggenerated
     */
    public void setProjectGroupId(Short projectGroupId) {
        this.projectGroupId = projectGroupId;
    }

    @Override
    public String toString() {
        return "LabacProjects{" +
                "projectId=" + projectId +
                ", projectName='" + projectName + '\'' +
                ", projectDesc='" + projectDesc + '\'' +
                ", projectCreateTime=" + projectCreateTime +
                ", projectUpdateTime=" + projectUpdateTime +
                ", projectComments='" + projectComments + '\'' +
                ", projectOwnerCustomerId=" + projectOwnerCustomerId +
                ", projectQuantity=" + projectQuantity +
                ", projectValue=" + projectValue +
                ", projectType=" + projectType +
                ", projectLocationFlag=" + projectLocationFlag +
                ", projectDisplaySize=" + projectDisplaySize +
                ", projectOrder=" + projectOrder +
                ", projectCategories='" + projectCategories + '\'' +
                ", projectFlag=" + projectFlag +
                ", projectIcon='" + projectIcon + '\'' +
                ", projectStatusIndicator=" + projectStatusIndicator +
                ", projectQuantityTried=" + projectQuantityTried +
                ", project3rdPartyReviewFlag=" + project3rdPartyReviewFlag +
                ", projectReviewInstruction='" + projectReviewInstruction + '\'' +
                ", projectRejectReasons=" + projectRejectReasons +
                ", projectReworkReasons=" + projectReworkReasons +
                ", projectPreapproveReasons=" + projectPreapproveReasons +
                ", projectDifficultyLevel=" + projectDifficultyLevel +
                ", projectCategories2='" + projectCategories2 + '\'' +
                ", projectPlanEndDate=" + projectPlanEndDate +
                ", projectActualEndDate=" + projectActualEndDate +
                ", saleId=" + saleId +
                ", projectSubject='" + projectSubject + '\'' +
                ", projectDetail='" + projectDetail + '\'' +
                ", projectMaxValue=" + projectMaxValue +
                ", projectIcon2='" + projectIcon2 + '\'' +
                ", projectCategoryFlag=" + projectCategoryFlag +
                ", projectLocationsFlag=" + projectLocationsFlag +
                ", projectGroupId=" + projectGroupId +
                '}';
    }
}